Wed 05 Jan 2022 03:29:43 PM CET

diff --git a/.github/workflows/run_integration_tests.yml b/.github/workflows/run_integration_tests.yml
--- a/.github/workflows/run_integration_tests.yml
+++ b/.github/workflows/run_integration_tests.yml
@@ -31,18 +31,13 @@ jobs:
           #working-directory: ./backend/setup_appwrite
           #run: |
           #./create-set-wallet-function.sh
-      # - name: set environment 
-      #   run: |
-      #     echo "export APPWRITE_ENDPOINT=http://localhost:80/v1" > ~/.bashrc
-      #     echo "export APPWRITE_PROJECT=$(cat ../setup_appwrite/project-id.txt)" > ~/.bashrc
-      #     echo "export APPWRITE_API_KEY=$(cat ../setup_appwrite/api-key.txt)" > ~/.bashrc
       - name: run python init script
         working-directory: ./backend/python_init_script
         run: |
           # source ~/.bashrc
           python3 -m pip install -r requirements.txt
           python3 main.py --apikey $(cat ../setup_appwrite/api-key.txt) --endpoint http://localhost:80/v1 --projectid $(cat ../setup_appwrite/project-id.txt) template.csv
-      - name: create-announcement-collection
+      - name: test create-announcement-collection
         working-directory: ./backend/database-collection-schemas
         run: |
           # Install deps
@@ -52,6 +47,21 @@ jobs:
           ret=$?
           if [ $ret -ne 0 ]; then
               echo "Something wrong create announcementCollection: error=$(ret)"
+              echo "Code 1: error creating collection"
+              echo "Code 2: error creating test data for collection"
+              exit 1
+          fi
+      - name: test create-wallets-collection
+        working-directory: ./backend/database-collection-schemas
+        run: |
+          # Install deps
+          python3 -m pip install -r requirements.txt
+          # Run the script
+          python3 createWalletsCollection.py --apikey $(cat ../setup_appwrite/api-key.txt) --endpoint http://localhost:80/v1 --projectid $(cat ../setup_appwrite/project-id.txt)
+          ret=$?
+          if [ $ret -ne 0 ]; then
+              echo "Something wrong create walletsCollection: error=$(ret)"
+              echo "Code 1: error creating collection"
               exit 1
           fi
       - name: setup frontend
