Wed 05 Jan 2022 03:21:56 PM CET

diff --git a/.github/workflows/run_integration_tests.yml b/.github/workflows/run_integration_tests.yml
--- a/.github/workflows/run_integration_tests.yml
+++ b/.github/workflows/run_integration_tests.yml
@@ -49,6 +49,11 @@ jobs:
           python3 -m pip install -r requirements.txt
           # Run the script
           python3 createAnnouncementCollection.py --apikey $(cat ../setup_appwrite/api-key.txt) --endpoint http://localhost:80/v1 --projectid $(cat ../setup_appwrite/project-id.txt)
+          ret=$?
+          if [ $ret -ne 0 ]; then
+              echo "Something wrong create announcementCollection: error=$(ret)"
+              exit 1
+          fi
       - name: setup frontend
         working-directory: ./frontend
         run: |
